tenancy_ocid        = "ocid1.tenancy.oc1..XXXX"
region              = "eu-frankfurt-1"
compartment_id      = "ocid1.compartment.oc1..XXXX"
application_name    = "performancetests"
object_storage_name = "phoronix"
